import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Activity as ActivityIcon, AlertCircle, AlertTriangle, CheckCircle2, Info, ShieldAlert } from 'lucide-react';
import CopyButton from '../components/CopyButton';
import DataTable, { type Column } from '../components/DataTable';
import { DetailItem, MobileRow } from '../components/DetailBlocks';
import FilterBar from '../components/FilterBar';
import FormModal from '../components/FormModal';
import PageContainer from '../components/PageContainer';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import StatusBadge from '../components/StatusBadge';
import Tabs from '../components/Tabs';
import { useStore } from '../store/useStore';
import type { ActivityEntry } from '../mock/activityLog';

type SeverityTab = 'all' | ActivityEntry['severity'];

const Activity = () => {
  const activityLog = useStore((state) => state.activityLog);
  const [searchParams, setSearchParams] = useSearchParams();

  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [severityTab, setSeverityTab] = useState<SeverityTab>('all');

  const selectedId = searchParams.get('selected');
  const selectedEntry = selectedId ? activityLog.find((entry) => entry.id === Number(selectedId)) ?? null : null;

  const openEntry = (entry: ActivityEntry) => {
    const next = new URLSearchParams(searchParams);
    next.set('selected', String(entry.id));
    setSearchParams(next);
  };

  const closeEntry = () => {
    const next = new URLSearchParams(searchParams);
    next.delete('selected');
    setSearchParams(next, { replace: true });
  };

  const counts = useMemo(() => {
    return {
      total: activityLog.length,
      info: activityLog.filter((entry) => entry.severity === 'info').length,
      success: activityLog.filter((entry) => entry.severity === 'success').length,
      warning: activityLog.filter((entry) => entry.severity === 'warning').length,
      error: activityLog.filter((entry) => entry.severity === 'error').length,
      security: activityLog.filter((entry) => entry.category === 'security').length,
    };
  }, [activityLog]);

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    return activityLog.filter((entry) => {
      const matchesSearch =
        !query ||
        entry.action.toLowerCase().includes(query) ||
        entry.description.toLowerCase().includes(query) ||
        entry.user.toLowerCase().includes(query);
      const matchesCategory = !categoryFilter || entry.category === categoryFilter;
      const matchesSeverity = severityTab === 'all' || entry.severity === severityTab;
      return matchesSearch && matchesCategory && matchesSeverity;
    });
  }, [activityLog, categoryFilter, search, severityTab]);

  const columns: Column<ActivityEntry>[] = [
    { key: 'action', label: 'Event', render: (_, row) => <EventCell entry={row} /> },
    { key: 'category', label: 'Category', render: (value) => <StatusBadge value={String(value)} /> },
    { key: 'severity', label: 'Severity', render: (value) => <StatusBadge value={String(value)} withIcon /> },
    { key: 'user', label: 'Actor' },
    { key: 'timestamp', label: 'Time' },
  ];

  return (
    <PageContainer>
      <PageHeader
        breadcrumbs={['CryptoGate', 'Activity']}
        description="Operational audit events generated by mock actions across the system."
        title="Activity Log"
      />

      <section className="mb-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <StatCard icon={ActivityIcon} subtitle="All events" title="Total" tone="cyan" value={counts.total} />
        <StatCard icon={Info} subtitle="Informational" title="Info" tone="blue" value={counts.info} />
        <StatCard icon={CheckCircle2} subtitle="Successful events" title="Success" tone="green" value={counts.success} />
        <StatCard icon={AlertTriangle} subtitle="Attention needed" title="Warnings" tone="amber" value={counts.warning} />
        <StatCard icon={ShieldAlert} subtitle="Security-related" title="Security" tone="rose" value={counts.security} />
      </section>

      <Tabs
        ariaLabel="Activity severity"
        items={[
          { value: 'all', label: 'All', count: counts.total },
          { value: 'info', label: 'Info', count: counts.info },
          { value: 'success', label: 'Success', count: counts.success },
          { value: 'warning', label: 'Warning', count: counts.warning },
          { value: 'error', label: 'Error', count: counts.error },
        ]}
        onChange={(value) => setSeverityTab(value as SeverityTab)}
        value={severityTab}
      />

      <FilterBar
        filters={[
          {
            label: 'All Categories',
            value: categoryFilter,
            onChange: setCategoryFilter,
            options: [
              { value: 'deposit', label: 'Deposits' },
              { value: 'wallet', label: 'Wallets' },
              { value: 'user', label: 'Users' },
              { value: 'api', label: 'API' },
              { value: 'system', label: 'System' },
              { value: 'security', label: 'Security' },
            ],
          },
        ]}
        onSearchChange={setSearch}
        searchPlaceholder="Search events..."
        searchValue={search}
      />

      <DataTable
        columns={columns}
        data={filtered}
        emptyDescription="Try clearing filters or generate new activity by editing mock records."
        emptyMessage="No activity entries found"
        onRowClick={openEntry}
        mobileRender={(entry) => (
          <article
            className="cursor-pointer rounded-lg border border-slate-800 bg-slate-900/70 p-4 transition hover:border-cyan-400/30 hover:bg-slate-900"
            onClick={() => openEntry(entry)}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') openEntry(entry);
            }}
            role="button"
            tabIndex={0}
          >
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0">
                <p className="truncate text-base font-bold text-white">{entry.action}</p>
                <p className="mt-1 line-clamp-2 text-sm text-slate-500">{entry.description}</p>
              </div>
              <StatusBadge value={entry.severity} withIcon />
            </div>
            <div className="mt-4 grid gap-2">
              <MobileRow label="Category" value={<StatusBadge value={entry.category} />} />
              <MobileRow label="Actor" value={entry.user} />
              <MobileRow label="Time" value={entry.timestamp} />
            </div>
          </article>
        )}
      />

      <FormModal
        description="Full activity details."
        isOpen={!!selectedEntry}
        onClose={closeEntry}
        title={selectedEntry ? selectedEntry.action : 'Activity Details'}
        size="lg"
      >
        {selectedEntry && (
          <div className="space-y-5">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <DetailItem label="Category" value={<StatusBadge value={selectedEntry.category} />} />
              <DetailItem label="Severity" value={<StatusBadge value={selectedEntry.severity} withIcon />} />
              <DetailItem label="Actor" value={selectedEntry.user} />
              <DetailItem label="Time" value={selectedEntry.timestamp} />
              <DetailItem label="ID" value={`#${selectedEntry.id}`} />
              <DetailItem label="IP Address" value={selectedEntry.ipAddress === '-' ? 'N/A' : selectedEntry.ipAddress} />
            </div>
            <div className="rounded-lg border border-slate-800 bg-slate-950/60 p-3">
              <p className="text-xs font-semibold uppercase text-slate-500">Description</p>
              <p className="mt-2 text-sm text-slate-200">{selectedEntry.description}</p>
            </div>
            {selectedEntry.ipAddress !== '-' && (
              <div className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-950/60 p-3">
                <div>
                  <p className="text-xs font-semibold uppercase text-slate-500">Copy IP</p>
                  <p className="mt-2 font-mono text-sm text-slate-200">{selectedEntry.ipAddress}</p>
                </div>
                <CopyButton label="ip address" value={selectedEntry.ipAddress} />
              </div>
            )}
          </div>
        )}
      </FormModal>
    </PageContainer>
  );
};

const severityIcon = (severity: ActivityEntry['severity']) => {
  if (severity === 'success') return <CheckCircle2 size={14} className="text-emerald-300" />;
  if (severity === 'warning') return <AlertTriangle size={14} className="text-amber-300" />;
  if (severity === 'error') return <AlertCircle size={14} className="text-rose-300" />;
  return <Info size={14} className="text-cyan-300" />;
};

const EventCell = ({ entry }: { entry: ActivityEntry }) => (
  <div className="min-w-0">
    <div className="flex items-center gap-2">
      {severityIcon(entry.severity)}
      <span className="truncate text-sm font-semibold text-white">{entry.action}</span>
    </div>
    <p className="mt-1 line-clamp-1 text-xs text-slate-500">{entry.description}</p>
  </div>
);

export default Activity;
